# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 
- bash: |
    if [ $(SECRET_ST) = "secret string" ]; then
        echo "Strings are equal."
    else
        echo "Strings are not equal."
    fi
  displayName: 'npm install and build'
  env:
    secret_st: $(secret)
  
